Bridge.assembly("Bridge.EasyTests", function ($asm, globals) {
    "use strict";


    var $m = Bridge.setMetadata,
        $n = [System,Bridge.EasyTests,System.Collections.Generic,System.Reflection,Bridge.EasyTests.Attributes];
    $m($n[1].App, function () { return {"att":1048577,"a":2,"m":[{"a":2,"isSynthetic":true,"n":".ctor","t":1,"sn":"ctor"},{"a":2,"n":"Main","is":true,"t":8,"sn":"Main","rt":$n[0].Void}]}; });
    $m($n[1].EasyAssert, function () { return {"att":1048577,"a":2,"m":[{"a":2,"isSynthetic":true,"n":".ctor","t":1,"sn":"ctor"},{"a":2,"n":"Description","t":16,"rt":$n[0].String,"g":{"a":2,"n":"get_Description","t":8,"rt":$n[0].String,"fg":"Description"},"s":{"a":2,"n":"set_Description","t":8,"p":[$n[0].String],"rt":$n[0].Void,"fs":"Description"},"fn":"Description"},{"a":2,"n":"Success","t":16,"rt":$n[0].Boolean,"g":{"a":2,"n":"get_Success","t":8,"rt":$n[0].Boolean,"fg":"Success","box":function ($v) { return Bridge.box($v, System.Boolean, System.Boolean.toString);}},"s":{"a":2,"n":"set_Success","t":8,"p":[$n[0].Boolean],"rt":$n[0].Void,"fs":"Success"},"fn":"Success"}]}; });
    $m($n[1].AssertResult, function () { return {"att":1048577,"a":2,"m":[{"a":1,"n":".ctor","t":1,"sn":"ctor"},{"a":2,"n":"WithAssert","t":8,"pi":[{"n":"assert","pt":Function,"ps":0},{"n":"description","pt":$n[0].String,"ps":1}],"sn":"WithAssert","rt":$n[1].AssertResult,"p":[Function,$n[0].String]},{"a":2,"n":"Asserts","t":16,"rt":$n[2].List$1(Bridge.EasyTests.EasyAssert),"g":{"a":2,"n":"get_Asserts","t":8,"rt":$n[2].List$1(Bridge.EasyTests.EasyAssert),"fg":"Asserts"},"fn":"Asserts"},{"a":2,"n":"Result","is":true,"t":16,"rt":$n[1].AssertResult,"g":{"a":2,"n":"get_Result","t":8,"rt":$n[1].AssertResult,"fg":"Result","is":true},"fn":"Result"}]}; });
    $m($n[1].TestDescriptor, function () { return {"att":1048576,"a":4,"m":[{"a":2,"n":".ctor","t":1,"sn":"ctor"},{"a":2,"n":"RunTest","t":8,"sn":"RunTest","rt":$n[0].Void},{"a":2,"n":"EasyAssertions","t":16,"rt":Bridge.virtualc("KnockoutObservableArray"),"g":{"a":2,"n":"get_EasyAssertions","t":8,"rt":Bridge.virtualc("KnockoutObservableArray"),"fg":"EasyAssertions"},"fn":"EasyAssertions"},{"a":2,"n":"Group","t":16,"rt":$n[0].String,"g":{"a":2,"n":"get_Group","t":8,"rt":$n[0].String,"fg":"Group"},"s":{"a":2,"n":"set_Group","t":8,"p":[$n[0].String],"rt":$n[0].Void,"fs":"Group"},"fn":"Group"},{"a":2,"n":"Instance","t":16,"rt":$n[0].Object,"g":{"a":2,"n":"get_Instance","t":8,"rt":$n[0].Object,"fg":"Instance"},"s":{"a":2,"n":"set_Instance","t":8,"p":[$n[0].Object],"rt":$n[0].Void,"fs":"Instance"},"fn":"Instance"},{"a":2,"n":"Method","t":16,"rt":$n[3].MethodInfo,"g":{"a":2,"n":"get_Method","t":8,"rt":$n[3].MethodInfo,"fg":"Method"},"s":{"a":2,"n":"set_Method","t":8,"p":[$n[3].MethodInfo],"rt":$n[0].Void,"fs":"Method"},"fn":"Method"},{"a":2,"n":"Name","t":16,"rt":$n[0].String,"g":{"a":2,"n":"get_Name","t":8,"rt":$n[0].String,"fg":"Name"},"fn":"Name"},{"a":2,"n":"Success","t":16,"rt":Bridge.virtualc("KnockoutObservable"),"g":{"a":2,"n":"get_Success","t":8,"rt":Bridge.virtualc("KnockoutObservable"),"fg":"Success"},"s":{"a":2,"n":"set_Success","t":8,"p":[Bridge.virtualc("KnockoutObservable")],"rt":$n[0].Void,"fs":"Success"},"fn":"Success"},{"a":2,"n":"Time","t":16,"rt":Bridge.virtualc("KnockoutObservable"),"g":{"a":2,"n":"get_Time","t":8,"rt":Bridge.virtualc("KnockoutObservable"),"fg":"Time"},"s":{"a":2,"n":"set_Time","t":8,"p":[Bridge.virtualc("KnockoutObservable")],"rt":$n[0].Void,"fs":"Time"},"fn":"Time"}]}; });
    $m($n[1].Prova, function () { return {"att":1048577,"a":2,"m":[{"a":2,"isSynthetic":true,"n":".ctor","t":1,"sn":"ctor"},{"at":[new Bridge.EasyTests.Attributes.TestMethodAttribute(null)],"a":2,"n":"Eccolo","t":8,"sn":"Eccolo","rt":$n[1].AssertResult},{"at":[new Bridge.EasyTests.Attributes.TestMethodAttribute(null)],"a":2,"n":"TeNo","t":8,"sn":"TeNo","rt":$n[1].AssertResult}]}; });
    $m($n[1].TestoTyutto, function () { return {"att":1048577,"a":2,"m":[{"a":2,"isSynthetic":true,"n":".ctor","t":1,"sn":"ctor"},{"at":[new Bridge.EasyTests.Attributes.TestMethodAttribute(null)],"a":2,"n":"TestSum","t":8,"sn":"TestSum","rt":$n[1].AssertResult},{"at":[new Bridge.EasyTests.Attributes.TestMethodAttribute(null)],"a":2,"n":"TestSum1","t":8,"sn":"TestSum1","rt":$n[1].AssertResult},{"at":[new Bridge.EasyTests.Attributes.TestMethodAttribute(null)],"a":2,"n":"TestSum2","t":8,"sn":"TestSum2","rt":$n[1].AssertResult},{"at":[new Bridge.EasyTests.Attributes.TestMethodAttribute(null)],"a":2,"n":"TestSum3","t":8,"sn":"TestSum3","rt":$n[1].AssertResult},{"at":[new Bridge.EasyTests.Attributes.TestMethodAttribute(null)],"a":2,"n":"TestSum4","t":8,"sn":"TestSum4","rt":$n[1].AssertResult},{"at":[new Bridge.EasyTests.Attributes.TestMethodAttribute(null)],"a":2,"n":"TestSum5","t":8,"sn":"TestSum5","rt":$n[1].AssertResult},{"at":[new Bridge.EasyTests.Attributes.TestMethodAttribute(null)],"a":2,"n":"TestSum6","t":8,"sn":"TestSum6","rt":$n[1].AssertResult}]}; });
    $m($n[1].Runner, function () { return {"att":1048576,"a":4,"m":[{"a":2,"n":".ctor","t":1,"sn":"ctor"},{"a":1,"n":"DiscoverTest","t":8,"sn":"DiscoverTest","rt":$n[0].Void},{"a":2,"n":"Run","t":8,"sn":"Run","rt":$n[0].Void},{"a":1,"n":"RunTests","t":8,"sn":"RunTests","rt":$n[0].Void},{"a":2,"n":"BrowserInfo","t":16,"rt":$n[0].String,"g":{"a":2,"n":"get_BrowserInfo","t":8,"rt":$n[0].String,"fg":"BrowserInfo"},"s":{"a":2,"n":"set_BrowserInfo","t":8,"p":[$n[0].String],"rt":$n[0].Void,"fs":"BrowserInfo"},"fn":"BrowserInfo"},{"a":2,"n":"FailedAsserts","t":4,"rt":Bridge.virtualc("KnockoutObservable"),"sn":"FailedAsserts"},{"a":2,"n":"PassedAsserts","t":4,"rt":Bridge.virtualc("KnockoutObservable"),"sn":"PassedAsserts"},{"a":2,"n":"Running","t":4,"rt":Bridge.virtualc("KnockoutObservable"),"sn":"Running"},{"a":2,"n":"Tests","t":4,"rt":Bridge.virtualc("KnockoutObservableArray"),"sn":"Tests"},{"a":2,"n":"TotalAssertions","t":4,"rt":Bridge.virtualc("KnockoutObservable"),"sn":"TotalAssertions"},{"a":2,"n":"TotalTime","t":4,"rt":Bridge.virtualc("KnockoutObservable"),"sn":"TotalTime"}]}; });
    $m($n[1].TestBase, function () { return {"att":1048705,"a":2,"m":[{"a":3,"isSynthetic":true,"n":".ctor","t":1,"sn":"ctor"},{"v":true,"a":2,"n":"Description","t":16,"rt":$n[0].String,"g":{"v":true,"a":2,"n":"get_Description","t":8,"rt":$n[0].String,"fg":"Description"},"fn":"Description"},{"a":3,"n":"Result","t":16,"rt":$n[1].AssertResult,"g":{"a":3,"n":"get_Result","t":8,"rt":$n[1].AssertResult,"fg":"Result"},"fn":"Result"}]}; });
    $m($n[4].TestAttribute, function () { return {"att":1048577,"a":2,"m":[{"a":2,"n":".ctor","t":1,"sn":"ctor"},{"a":2,"n":".ctor","t":1,"p":[$n[0].String],"pi":[{"n":"description","pt":$n[0].String,"ps":0}],"sn":"$ctor1"},{"a":2,"n":"Description","t":16,"rt":$n[0].String,"g":{"a":2,"n":"get_Description","t":8,"rt":$n[0].String,"fg":"Description"},"fn":"Description"}]}; });
    $m($n[4].TestMethodAttribute, function () { return {"att":1048577,"a":2,"m":[{"a":2,"n":".ctor","t":1,"p":[$n[0].String],"pi":[{"n":"description","dv":null,"o":true,"pt":$n[0].String,"ps":0}],"sn":"ctor"},{"a":2,"n":"Description","t":16,"rt":$n[0].String,"g":{"a":2,"n":"get_Description","t":8,"rt":$n[0].String,"fg":"Description"},"fn":"Description"}]}; });
});
